import { useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";
import { Eyebrow } from "./Atoms.jsx";
import { DISCOVERY, DISCOVERY_CATEGORIES, VOIDCALLER_CATALOG } from "../data.js";
import { getArtistCatalog, getEditionCatalog, getReleaseCatalog } from "../domain/models.js";
import { supportedGatewayMediaType } from "../lib/experience-service.js";
import { ListingPanel } from "./ListingPanel.jsx";
import { PurchasePanel } from "./PurchasePanel.jsx";

const shell = { maxWidth: 1100, margin: "0 auto", padding: "clamp(120px, 16vw, 180px) clamp(20px, 5vw, 48px)" };
const card = { border: "1px solid var(--vc-ash)", background: "var(--vc-abyss)", padding: "24px" };
const button = { display: "inline-block", border: "1px solid var(--vc-bone-dim)", color: "var(--vc-bone)", padding: "11px 16px", fontFamily: "var(--font-mono)", fontSize: 11, letterSpacing: ".12em", textTransform: "uppercase", textDecoration: "none" };
function PlatformHeader({ eyebrow, title, children }) { return <header style={{ marginBottom: 48 }}><Eyebrow red>{eyebrow}</Eyebrow><h1 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(48px, 9vw, 92px)", lineHeight: .92, textTransform: "uppercase", margin: "16px 0" }}>{title}</h1>{children}</header>; }
function Status({ children }) { return <span style={{ color: "var(--vc-crimson)", fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase" }}>{children}</span>; }
function ReleaseCard({ release }) { return <Link key={release.id} to={`/release/${release.id}`} style={{ ...card, display: "block", color: "inherit", textDecoration: "none" }}><Status>{release.status}</Status><h2 style={{ fontFamily: "var(--font-display)", fontSize: 30, margin: "12px 0 8px" }}>{release.title}</h2><p style={{ color: "var(--vc-bone-dim)", margin: 0 }}>{release.subtitle}</p></Link>; }
function EditionCard({ edition }) { return <Link key={edition.id} to={`/edition/${edition.id}`} style={{ ...card, display: "block", color: "inherit", textDecoration: "none" }}><Status>{edition.status}</Status><h3 style={{ fontFamily: "var(--font-display)", fontSize: 24, margin: "12px 0 8px" }}>{edition.title}</h3><p style={{ color: "var(--vc-bone-dim)", margin: 0 }}>{edition.supply || "Open supply"} · {edition.chain}</p></Link>; }
function ExperienceList({ experiences = [] }) { return <div style={{ display: "grid", gap: 12 }}>{experiences.map((experience) => <Link key={experience.id} to={`/experience/${experience.id}`} style={{ ...card, padding: 18, color: "inherit", textDecoration: "none" }}><Status>{experience.experienceType} · {experience.requirements?.length ? "Ownership gated" : "Open access"}</Status><h3 style={{ fontFamily: "var(--font-display)", fontSize: 24, margin: "10px 0 6px" }}>{experience.title}</h3><p style={{ color: "var(--vc-bone-dim)", margin: 0 }}>{experience.description}</p>{experience.media?.protected && <p style={{ color: "var(--vc-bone-dim)", fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".1em", marginBottom: 0 }}>PROTECTED MEDIA · COLLECTOR AUTHORIZATION REQUIRED</p>}</Link>)}</div>; }

export function DiscoverPage() {
  const [category, setCategory] = useState("featured");
  const ids = DISCOVERY[category] || [];
  const isArtistCategory = category === "artists";
  const records = isArtistCategory ? VOIDCALLER_CATALOG.artists.filter((artist) => ids.includes(artist.id)) : category === "limited-editions" ? VOIDCALLER_CATALOG.editions.filter((edition) => ids.includes(edition.id)) : VOIDCALLER_CATALOG.releases.filter((release) => ids.includes(release.id));
  return <section style={shell}><PlatformHeader eyebrow="† DISCOVERY" title="Find the next record"><p style={{ color: "var(--vc-bone-dim)", maxWidth: 600 }}>A deterministic index of artists, releases, editions, and live musical experiences. No recommendations, no marketplace noise.</p></PlatformHeader><nav aria-label="Discovery categories" style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 28 }}>{DISCOVERY_CATEGORIES.map((item) => <button key={item} onClick={() => setCategory(item)} style={{ ...button, cursor: "pointer", background: category === item ? "var(--vc-crimson)" : "transparent", borderColor: category === item ? "var(--vc-crimson)" : "var(--vc-ash)" }}>{item.replace("-", " ")}</button>)}</nav><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>{records.map((record) => isArtistCategory ? <Link key={record.id} to={`/artist/${record.id}`} style={{ ...card, color: "inherit", textDecoration: "none" }}><Eyebrow>ARTIST #{record.artistNumber}</Eyebrow><h2 style={{ fontFamily: "var(--font-display)", fontSize: 30 }}>{record.name}</h2><p style={{ color: "var(--vc-bone-dim)" }}>{record.bio}</p></Link> : category === "limited-editions" ? <EditionCard key={record.id} edition={record} /> : <ReleaseCard key={record.id} release={record} />)}</div></section>;
}

export function ArtistsPage() { return <section style={shell}><PlatformHeader eyebrow="† ARTISTS" title="Artists"><p style={{ color: "var(--vc-bone-dim)" }}>Artists are the roots of every release and experience.</p></PlatformHeader><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>{VOIDCALLER_CATALOG.artists.map((artist) => <Link key={artist.id} to={`/artist/${artist.id}`} style={{ ...card, color: "inherit", textDecoration: "none" }}><Eyebrow>ARTIST #{artist.artistNumber}</Eyebrow><h2 style={{ fontFamily: "var(--font-display)", fontSize: 32, margin: "12px 0 0" }}>{artist.name}</h2><p style={{ color: "var(--vc-bone-dim)" }}>@{artist.handle} · {artist.verified ? "Verified" : "Unverified"}</p></Link>)}</div></section>; }

export function ArtistPage() {
  const { artist: artistId } = useParams();
  const result = getArtistCatalog(VOIDCALLER_CATALOG, artistId);
  if (!result) return <Navigate to="/artists" replace />;
  const { artist, releases, editions, collections } = result;
  return <section style={shell}><div style={{ ...card, minHeight: 280, backgroundImage: `linear-gradient(180deg, rgba(0,0,0,.2), rgba(0,0,0,.85)), url(${artist.banner})`, backgroundSize: "cover", backgroundPosition: "center", display: "flex", flexDirection: "column", justifyContent: "flex-end" }}><Status>{artist.verified ? "Verified artist" : "Artist"}</Status><h1 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(52px, 10vw, 100px)", margin: "12px 0 4px", textTransform: "uppercase" }}>{artist.name}</h1><p style={{ fontFamily: "var(--font-mono)", color: "var(--vc-bone-dim)", margin: 0 }}>@{artist.handle} · Artist #{artist.artistNumber}</p></div><div style={{ maxWidth: 650, margin: "28px 0 56px", color: "var(--vc-bone-dim)", lineHeight: 1.7 }}><p>{artist.bio}</p>{artist.socials.map((social) => <a key={social.name} href={social.href} target="_blank" rel="noreferrer" style={{ color: "var(--vc-bone)", marginRight: 18 }}>{social.name}</a>)}</div><Eyebrow>RELEASES</Eyebrow><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16, margin: "16px 0 48px" }}>{releases.map((release) => <ReleaseCard key={release.id} release={release} />)}</div><Eyebrow>EDITIONS & COLLECTIONS</Eyebrow><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16, marginTop: 16 }}>{editions.map((edition) => <EditionCard key={edition.id} edition={edition} />)}{collections.map((collection) => <div key={collection.id} style={card}><Status>Collection</Status><h3 style={{ fontFamily: "var(--font-display)", fontSize: 24 }}>{collection.name}</h3><p style={{ color: "var(--vc-bone-dim)" }}>{collection.description}</p></div>)}</div></section>;
}

export function ReleasePage() {
  const { release: releaseId } = useParams();
  const result = getReleaseCatalog(VOIDCALLER_CATALOG, releaseId);
  if (!result) return <Navigate to="/discover" replace />;
  const { release, artist, editions } = result;
  return <section style={shell}><PlatformHeader eyebrow="† RELEASE · MUSIC FIRST" title={release.title}><p style={{ color: "var(--vc-bone-dim)", maxWidth: 650 }}>{release.description}</p><p><Link to={`/artist/${artist.id}`} style={{ color: "var(--vc-bone)" }}>{artist.name}</Link> · <Status>{release.status}</Status></p></PlatformHeader><div style={{ display: "grid", gridTemplateColumns: "minmax(220px, .8fr) minmax(280px, 1.2fr)", gap: 32, alignItems: "start" }}><img src={release.artwork} alt={`${release.title} artwork`} style={{ width: "100%", aspectRatio: "1", objectFit: "cover" }} /><div><Eyebrow>THE STORY</Eyebrow><p style={{ color: "var(--vc-bone-dim)", lineHeight: 1.7 }}>{release.story}</p><Eyebrow>TRACKS</Eyebrow><ol style={{ color: "var(--vc-bone-dim)", lineHeight: 2 }}>{release.tracks.map((track) => <li key={track.n}>{track.title} <span style={{ opacity: .6 }}>· {track.time}</span></li>)}</ol></div></div><h2 style={{ fontFamily: "var(--font-display)", fontSize: 42, marginTop: 72 }}>EDITIONS</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 }}>{editions.length ? editions.map((edition) => <EditionCard key={edition.id} edition={edition} />) : <div style={card}><Status>Forthcoming</Status><p style={{ color: "var(--vc-bone-dim)" }}>Editions will appear here when this release is collectible.</p></div>}</div>{release.experiences?.length > 0 && <><h2 style={{ fontFamily: "var(--font-display)", fontSize: 42, marginTop: 72 }}>EXPERIENCES</h2><ExperienceList experiences={result.experiences} /></>}</section>;
}

export function EditionPage() {
  const { edition: editionId } = useParams();
  const result = getEditionCatalog(VOIDCALLER_CATALOG, editionId);
  if (!result) return <Navigate to="/discover" replace />;
  const { edition, release, artist, experiences } = result;
  return <section style={shell}><PlatformHeader eyebrow={`† EDITION · ${edition.tier.toUpperCase()}`} title={edition.title}><p style={{ color: "var(--vc-bone-dim)", maxWidth: 650 }}>{edition.description}</p><p><Link to={`/release/${release.id}`} style={{ color: "var(--vc-bone)" }}>{release.title}</Link> · <Link to={`/artist/${artist.id}`} style={{ color: "var(--vc-bone)" }}>{artist.name}</Link></p></PlatformHeader><div style={{ ...card, display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 28 }}><div><Eyebrow>COLLECTOR RECEIVES</Eyebrow><ul style={{ color: "var(--vc-bone-dim)", lineHeight: 2 }}>{edition.includes.map((item) => <li key={item}>{item}</li>)}</ul>{edition.valueProposition && <p style={{ color: "var(--vc-bone)" }}>{edition.valueProposition}</p>}</div><div><Eyebrow>EDITION DETAILS</Eyebrow><p style={{ color: "var(--vc-bone-dim)" }}>Status: <strong>{edition.status}</strong><br />Supply: <strong>{edition.supply}</strong><br />Chain: <strong>{edition.chain}</strong></p><p style={{ color: "var(--vc-bone-dim)", fontSize: 12 }}>ERC-1155 infrastructure · {edition.tokenIds.length} token IDs represented</p><Link to="/reliquary" style={button}>Open collector experience</Link></div></div><h2 style={{ fontFamily: "var(--font-display)", fontSize: 42, marginTop: 72 }}>WHAT THIS UNLOCKS</h2><ExperienceList experiences={experiences} /><PurchasePanel edition={edition} /><ListingPanel edition={edition} /></section>;
}

export function ExperiencePage() {
  const { experience: experienceId } = useParams();
  const experience = VOIDCALLER_CATALOG.experiences.find((item) => item.id === experienceId);
  if (!experience) return <Navigate to="/discover" replace />;
  const protectedMedia = experience.media?.protected && supportedGatewayMediaType(experience.media?.type?.toUpperCase());
  const access = experience.requirements?.length ? "COLLECTOR AUTHORIZATION REQUIRED" : "OPEN EXPERIENCE";
  return <section style={shell}><PlatformHeader eyebrow="† EXPERIENCE" title={experience.title}><p style={{ color: "var(--vc-bone-dim)", maxWidth: 650 }}>{experience.description}</p></PlatformHeader><div style={{ ...card, maxWidth: 720 }}><Status>{access}</Status><h2 style={{ fontFamily: "var(--font-display)", fontSize: 38, margin: "14px 0" }}>Access boundary</h2><p style={{ color: "var(--vc-bone-dim)", lineHeight: 1.7 }}>{protectedMedia ? "This experience is delivered by the production media gateway. Connect a wallet, sign a one-time challenge, and the server verifies current ownership before issuing a short-lived grant." : "This experience is available without protected media authorization."}</p>{protectedMedia && <ul style={{ color: "var(--vc-bone-dim)", lineHeight: 1.9 }}><li>Challenge bound to wallet, experience, and nonce</li><li>Ownership checked server-side against the current index</li><li>Grant expires after five minutes and never exposes origin media URLs</li><li>Access decisions are written to the download audit ledger</li></ul>}<p style={{ fontFamily: "var(--font-mono)", fontSize: 10, letterSpacing: ".12em", color: "var(--vc-bone-dim)" }}>{protectedMedia ? "GATEWAY STATUS · AUTHORIZATION CONTRACT READY" : "DELIVERY STATUS · PUBLIC"}</p></div></section>;
}
export function CollectionPage() { return <section style={shell}><PlatformHeader eyebrow="† COLLECTION" title="My Collection"><p style={{ color: "var(--vc-bone-dim)" }}>Your owned editions and token-native experiences will gather here.</p></PlatformHeader><Link style={button} to="/reliquary">Open reliquary</Link></section>; }
export function CollectorsPage() { return <section style={shell}><PlatformHeader eyebrow="† COLLECTORS" title="Collectors"><p style={{ color: "var(--vc-bone-dim)" }}>A future home for collector identity and earned experiences.</p></PlatformHeader><Link style={button} to="/collection">View my collection</Link></section>; }
