import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { ethers } from "ethers";
if ((process.env.DEPLOY_NETWORK || "fuji") !== "fuji") throw new Error("This script only deploys VoidRelease1155 to Avalanche Fuji (43113).");
const rpcUrl = process.env.AVALANCHE_FUJI_RPC_URL;
const privateKey = process.env.DEPLOYER_PRIVATE_KEY;
const admin = process.env.RELEASE_ADMIN_ADDRESS;
if (!rpcUrl || !privateKey || !/^0x[a-fA-F0-9]{40}$/.test(admin || "")) throw new Error("Required: AVALANCHE_FUJI_RPC_URL, DEPLOYER_PRIVATE_KEY, RELEASE_ADMIN_ADDRESS.");
const artifact = JSON.parse(await readFile("out/VoidRelease1155.sol/VoidRelease1155.json", "utf8"));
const provider = new ethers.JsonRpcProvider(rpcUrl, 43113, { staticNetwork: true });
const deployer = new ethers.Wallet(privateKey, provider);
const network = await provider.getNetwork();
if (network.chainId !== 43113n) throw new Error(`Refusing non-Fuji chain: ${network.chainId}`);
const factory = new ethers.ContractFactory(artifact.abi, artifact.bytecode.object, deployer);
const contract = await factory.deploy(admin);
const deploymentTransaction = contract.deploymentTransaction();
if (!deploymentTransaction) throw new Error("Deployment transaction was not created.");
const receipt = await deploymentTransaction.wait();
if (!receipt || receipt.status !== 1) throw new Error("Deployment transaction did not receive a successful receipt.");
const address = await contract.getAddress();
const transactionHash = deploymentTransaction.hash;
const bytecodeHash = `0x${createHash("sha256").update(Buffer.from(artifact.bytecode.object.replace(/^0x/, ""), "hex")).digest("hex")}`;
const resultRecord = { network: "fuji", chainId: 43113, contractType: "ERC1155", contractName: "VoidRelease1155", contractAddress: address.toLowerCase(), deploymentTransaction: transactionHash.toLowerCase(), deploymentBlock: receipt.blockNumber, deployer: deployer.address.toLowerCase(), admin: admin.toLowerCase(), bytecodeHash, artifact: "out/VoidRelease1155.sol/VoidRelease1155.json" };
const outputPath = process.env.DEPLOY_RESULT_FILE || "/tmp/release-fuji-pending.json";
await writeFile(outputPath, `${JSON.stringify(resultRecord, null, 2)}\n`);
console.log(JSON.stringify({ ...resultRecord, resultFile: outputPath }, null, 2));
