/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as ArtistsSlugRouteImport } from './routes/artists/$slug'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as ReviewIdRouteImport } from './routes/review/$id'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyApplyRouteImport } from './routes/verify/apply'
import { Route as VerifyReceivedRouteImport } from './routes/verify/received'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyApplyRoute = VerifyApplyRouteImport.update({
  id: '/verify/apply',
  path: '/verify/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReceivedRoute = VerifyReceivedRouteImport.update({
  id: '/verify/received',
  path: '/verify/received',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/review/$id': typeof ReviewIdRoute
  '/verify/apply': typeof VerifyApplyRoute
  '/verify/received': typeof VerifyReceivedRoute
  '/artists/': typeof ArtistsIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/review/$id': typeof ReviewIdRoute
  '/verify/apply': typeof VerifyApplyRoute
  '/verify/received': typeof VerifyReceivedRoute
  '/artists': typeof ArtistsIndexRoute
  '/review': typeof ReviewIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/review/$id': typeof ReviewIdRoute
  '/verify/apply': typeof VerifyApplyRoute
  '/verify/received': typeof VerifyReceivedRoute
  '/artists/': typeof ArtistsIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/artists/$slug'
    | '/review/$id'
    | '/verify/apply'
    | '/verify/received'
    | '/artists/'
    | '/review/'
    | '/verify/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/artists/$slug'
    | '/review/$id'
    | '/verify/apply'
    | '/verify/received'
    | '/artists'
    | '/review'
    | '/verify'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/artists/$slug'
    | '/review/$id'
    | '/verify/apply'
    | '/verify/received'
    | '/artists/'
    | '/review/'
    | '/verify/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  ReviewIdRoute: typeof ReviewIdRoute
  VerifyApplyRoute: typeof VerifyApplyRoute
  VerifyReceivedRoute: typeof VerifyReceivedRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/apply': {
      id: '/verify/apply'
      path: '/verify/apply'
      fullPath: '/verify/apply'
      preLoaderRoute: typeof VerifyApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/received': {
      id: '/verify/received'
      path: '/verify/received'
      fullPath: '/verify/received'
      preLoaderRoute: typeof VerifyReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  ReviewIdRoute: ReviewIdRoute,
  VerifyApplyRoute: VerifyApplyRoute,
  VerifyReceivedRoute: VerifyReceivedRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
